FROM node:lts-alpine

RUN mkdir -p /app
WORKDIR /app
COPY package*.json ./
RUN apk --no-cache add --virtual builds-deps build-base python3 git
RUN yarn install
ENV NODE_ENV dev
ENV NODE_ICU_DATA=node_modules/full-icu
ENTRYPOINT [ "yarn", "run", "dev"]