FROM node:10.15.2-alpine

RUN npm install --unsafe-perm -g full-icu
ENV NODE_ICU_DATA="/usr/local/lib/node_modules/full-icu"
RUN mkdir -p /app
WORKDIR /app
COPY package*.json ./
RUN apk --no-cache add --virtual builds-deps build-base python
RUN npm install
ENV NODE_ENV dev
ENTRYPOINT [ "npm", "run", "dev"]